### ISSUE TITLE
Create fake for IHealth interface

### ISSUE THREAD

**Issue by shawnHartsell** [InVisionApp/go-health#42]

**Comment by shawnHartsell** [comment]
@dselans I was able to get around this by creating an instance of the ```Health``` struct, but it would be nice to have a fake for this. Unfortunately, since ```IHealth``` uses  the```Config``` struct we'll have circular references when generating the fake.

Since the refactoring to make this happen would have negative affects on consumers, I wanted to get some of your feedback before I started hacking away at it 🤣

**Comment by dselans** [comment]
@shawnHartsell Can you explain what you mean by circular references? If the goal is to be able to inject a fake instance of IHealth (so that .AddChecks and .Start do not have any effect), generating and including a fake in this lib, seem okay?

Where are you seeing the problem?

**Comment by dselans** [comment]
Generating a fake for `IHealth` should work without issues. We briefly talked about this report offline, but I don't recall exactly what we arrived at. If it's still an issue, let's open up another issue w/ a full example use case.
