### ISSUE TITLE
Data race in states handling

### ISSUE THREAD

**Issue by dlecorfec** [InVisionApp/go-health#45]
Hello,

You may want to review your mutex usage around map[string]State in health.go, as safeGetStates() is *not* safe: you safely copy a *pointer* to the map by returning the map value, but it is the access to the individual elements of the map that you should protect (or safely deep-copy the map on each read access, but it may be heavy-handed ;). Confirmed with the go race detector with a dummy check, and polling a /ready route.

```
func main() {
        h := health.New()

        h.AddChecks([]*health.Config{
                {
                        Name:     "my-check",
                        Checker:  foo{},
                        Interval: time.Duration(1) * time.Second,
                        Fatal:    true,
                },
        })
        h.Start()
        http.Handle("/ready", handlers.NewJSONHandlerFunc(h, nil))
        http.ListenAndServe(":8020", nil)
}
```

Side-note, I was taking a look at the various health packages, maybe https://github.com/heptiolabs/healthcheck/ could be a good fit for you, it seems simpler (less packages/smaller API) but powerful and bugfree, and less open source packages to maintain (for you) or evaluate (for me) is often better ;)

Best regards,
David

(updated: no need for a 1 ms check interval and using wrk in order to trigger the go race detector, 1s and a single curl is enough ;)

**Comment by dselans** [comment]
Fixed in #46 + added an additional test + fixed a leak.

Thanks for the report @dlecorfec !
