### ISSUE TITLE
Ideally checkers with external dependencies should live in a different package

### ISSUE THREAD

**Issue by maxcnunes** [InVisionApp/go-health#56]
For instance, I just need to use the reachable checker and my project doesn't have any mongo dep. But, to use the reachable checker I need to install all dependencies in `InVisionApp/go-health/checker` and the mongo one has a dependency on github.com/globalsign/mgo. If the checkers that have some external dependency were in a different package it wouldn't force me to have a dependency on something that I'm not using.
No need to move them to a different repository, just having them a subfolder would be enough to avoid this dependency issue.
I can create a PR for it, but it would cause a breaking change in the project.

Suggested packages:
* `InVisionApp/go-health/checker` no external deps
* `InVisionApp/go-health/checker/mongo`
* `InVisionApp/go-health/checker/redis`
* `InVisionApp/go-health/checker/disk`
* `InVisionApp/go-health/checker/memcache`

**Comment by dselans** [comment]
@maxcnunes This was definitely discussed when we initially started the project - the idea was that it'd be _annoying_ to specify & import every single checker (if your application used multiple deps). Now that there's a bunch of checkers, this seems like a misstep.

I'm cool with it - open a PR and we can cut a new (breaking) release.

**Comment by dselans** [comment]
All done - `2.0.0` release cut. Thanks @maxcnunes !
