### ISSUE TITLE
Metrics Endpoint

### ISSUE THREAD

**Issue by zbindenren** [InVisionApp/go-health#60]
Would a pull request accepted that adds [prometheus](https://prometheus.io/)  support?

I was thinking of something that returns:

```
# HELP healthcheck_failed A counter that shows number of failed checks.
# TYPE healthcheck_failed counter
healthcheck_failed{check="ping", fatal="true} 3
```

**Comment by dselans** [comment]
I no longer have maintainer access in this repo, but I don't see why not -- I'll ping someone to take a look at this when you get it in.

**Comment by schigh** [comment]
@zbindenren I will start prioritizing this.  Apologies for the late response.

**Comment by maxcnunes** [comment]
This project is no longer actively supported and will be archived. Therefore all issues and pull requests are being closed. Please, feel free to fork it and apply the proposed change.
