### ISSUE TITLE
GRPC Checkers

### ISSUE THREAD

**Issue by dharmjit** [InVisionApp/go-health#61]
Hi Team, Thanks for this awesome library. Is there a way to add grpc checkers with the current package.

**Comment by dselans** [comment]
Hey there! Yes, it's super easy to add custom checkers - all you have to do is pass in something that satisfies the [ICheckable](https://github.com/InVisionApp/go-health/blob/master/health.go#L47) interface.

Here's an example: https://github.com/InVisionApp/go-health/blob/master/examples/custom-checker-server/custom-checker-server.go
