### ISSUE TITLE
Degraded state?

### ISSUE THREAD

**Issue by tangtony** [InVisionApp/go-health#63]
When a non-fatal check fails, the top level status is still "ok". Is the intent that you have to check each component for success in order to determine if the service is actually 100% ok?

Would it be possible to add support for a degraded state or something along the lines of "there are failures, but nothing fatal"?

**Comment by schigh** [comment]
@tangtony apologies for the late response.

I do like this idea.  Could you maybe expand upon it a bit?  I'm thinking in terms of how to best use that information in a consumer...a readiness probe for example.  How could we unambiguously say "there are some failures, but nothing fatal" to a listening process?

**Comment by dselans** [comment]
I think that's exactly it - if a non-fatal service fails, then the lib can return a 2xx (other than 200) and a JSON status of `degraded`. Seems legit?

**Comment by maxcnunes** [comment]
This project is no longer actively supported and will be archived. Therefore all issues and pull requests are being closed. Please, feel free to fork it and apply the proposed change.
