### ISSUE TITLE
Persist checkers state?

### ISSUE THREAD

**Issue by gen2brain** [InVisionApp/go-health#66]
Hi,

I would like to persist checkers state, so if some check was in the failed state after I restart service I would like to still be in a failed state and to expect recover. I can use map from `State()` to save that to some JSON file, but I don't see a way to set it for checker before `Start()`. Is this possible?

Thanks,
Milan

**Comment by gen2brain** [comment]
I solved this by adding `LoadState`, like this https://github.com/gen2brain/go-health/commit/fd2225e1f326134d0f30418592ddae1a77de2347, and it works as expected.

Still, I would prefer to not use my fork.

**Comment by schigh** [comment]
@gen2brain apologies for the late response.  I will look into this and prioritize it.

**Comment by dselans** [comment]
This totally makes sense. Should definitely have this functionality.

**Comment by maxcnunes** [comment]
This project is no longer actively supported and will be archived. Therefore all issues and pull requests are being closed. Please, feel free to fork it and apply the proposed change.
