### ISSUE TITLE
add remote server health checker

### ISSUE THREAD

**Issue by aronlt** [InVisionApp/go-health#75]
In many cases, we need to check remote server status, such as cpu usage percentage, memory usage percentage. I hope this project add this feature. thanks

**Comment by dselans** [comment]
How would this information be exposed by the remote service?

**Comment by maxcnunes** [comment]
This project is no longer actively supported and will be archived. Therefore all issues and pull requests are being closed. Please, feel free to fork it and apply the proposed change.
