### ISSUE TITLE
Indentation for JSON in NewJSONHandlerFunc

### ISSUE THREAD

**Issue by antonjah** [InVisionApp/go-health#76]
When using go-health together with gin-gonic I'm finding it hard to format the JSON output from `NewJSONHandlerFunc()`.
Would it be possible to update the signature of `NewJSONHandlerFunc()` to include some kind of config? I don't really know what approach that would be the best, but some pseudo examples:

```go
func NewJSONHandlerFunc(h health.IHealth, custom map[string]interface{}, formatConfig *health.FomatConfig) http.HandlerFunc {
    ...

    encoder := json.NewEncoder(...)
    if formatConfig != nil {
        encoder.SetIndent(formatConfig.Prefix, formatConfig.Indent)
    }
    json.Encode(...)
}
```

Or something simple like:

```go
func NewJSONHandlerFunc(h health.IHealth, custom map[string]interface{}, prefix, indent string) http.HandlerFunc {
    ...
    data, err := json.MarshalIndent(fullBody.data, prefix, indent)
}
```

Like I said, I don't know the best (go) approach for this. And if this is possible somehow already I would be happy for all the information I can get.

Thanks for a very nice project.

**Comment by maxcnunes** [comment]
This project is no longer actively supported and will be archived. Therefore all issues and pull requests are being closed. Please, feel free to fork it and apply the proposed change.
