### ISSUE TITLE
Uses no longer accessible dependencies

### ISSUE THREAD

**Issue by acabarbaye** [InVisionApp/go-health#79]
**Describe the bug**
`go-health` depends on [mongodb-boltdb-mock](github.com/zaffka/mongodb-boltdb-mock) which is no longer accessible

Although this dependency is not used directly, it stops dependabot from working properly as it appears in the go.sum file of the projects depending on `go-health`
![image](https://user-images.githubusercontent.com/29707928/194308907-ca54563b-297b-46ff-9bb0-59bad1b22657.png)

Could the dependency be removed and an alternative chosen?

**Comment by codyaray** [comment]
This broke multiple builds at my company. :(

In addition to opening the issue above^, I've also emailed the author directly (hint: check the commit logs on other repos). Maybe we can get him to bring this back until someone at InVisionApp can remove this dependency.

**Comment by zaffka** [comment]
Guys, I'm so sorry. At the time I've been creating the repo I thought nobody will use it.   
If it helps - recreated the repo from cache @codyaray Cody sent me.

**Comment by Radisovik** [comment]
> Guys, I'm so sorry. At the time I've been creating the repo I thought nobody will use it. If it helps - recreated the repo from cache @codyaray Cody sent me.

Thanks!

**Comment by Radisovik** [comment]
Is the damage already done though?  since the commit hashes changed?

**Comment by soumiksamanta** [comment]
When can we expect a release with the updated commit hash? As a workaround, I have to update the replace directive for all my projects.

**Comment by ivan-santos-eq** [comment]
https://github.com/zaffka/mongodb-boltdb-mock is back, but the commit SHA has changed.

**Comment by ivan-santos-eq** [comment]
https://github.com/InVisionApp/go-health/pull/81

**Comment by chesleybrown** [comment]
Thanks for the reminder. 😊

Done in https://github.com/InVisionApp/go-health/releases/tag/v2.1.3 ✅
